import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })
page.on('console', (msg) => console.log('BROWSER', msg.type(), msg.text()))
await page.goto('http://127.0.0.1:5173')
await page.evaluate(() => localStorage.clear())
await page.reload()
await page.getByRole('button', { name: /Isabella/i }).click()
await page.waitForURL('**/dashboard')
await page.getByRole('button', { name: /Teclea como una experta/i }).click()
await page.waitForURL('**/games/teclea-como-una-experta')
await page.getByRole('button', { name: /Teclas A S D/i }).click()
await page.waitForURL('**/lesson/typing-l1-a')
await page.waitForTimeout(500)
await page.getByLabel('Teclado virtual').getByRole('button', { name: 'A', exact: true }).click()
await page.waitForTimeout(1000)
const text = await page.locator('body').innerText()
console.log('MATCH', text.match(/Actividad .*|Presiona la tecla .|¡Muy bien!/g))
await page.screenshot({ path: '/tmp/typing-debug.png', fullPage: true })
// try keyboard
await page.keyboard.press('S')
await page.waitForTimeout(1000)
console.log('AFTER S', (await page.locator('body').innerText()).match(/Actividad .*|Presiona la tecla .|¡Muy bien!/g))
await browser.close()
